DjangoTemlate/App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^hello/', views.hello),
    url(r'^index/', views.index),
    url(r'^getstudents/', views.get_students),
]

DjangoTemlate/DjangoTemlate/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('App.urls')),
    url(r'^two/', include('Two.urls', namespace='second')),
]

DjangoTemlate/Two/urls.py
from django.conf.urls import url

from Two import views

urlpatterns = [
    # url(r'^students/(\d+)/', views.student),

    url(r'^grades/', views.grades),
    url(r'^students/(\d+)/', views.students, name='get_students'),
    url(r'^gettime/(\d+)/(\d+)/(\d+)/', views.get_time, name='get_time'),
    url(r'^getdate/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/', views.get_date, name='get_date'),
    url(r'^learn/', views.learn, name='learn'),
    url(r'^studentpage/(\d+)/', views.get_studentpage, name='get_studentpage'),
    url(r'^deletestudent/(\d+)/', views.delete_student, name='delete_student'),
    url(r'^addstudent/', views.add_student, name='add_student'),
    url(r'^haverequest/', views.have_request),

    url(r'^test/', views.test),
]

DjangoTemlate/App/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    s_name = models.CharField(max_length=16)

    def get_name(self):
        return self.s_name

DjangoTemlate/Two/models.py
from django.db import models

# Create your models here.
class Grade(models.Model):
    g_name = models.CharField(max_length=16)


class Student(models.Model):
    s_name = models.CharField(max_length=16)
    is_delete = models.BooleanField(default=False)
    s_grade = models.ForeignKey(Grade)

DjangoTemlate/App/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader

from App.models import Student


def hello(request):
    return HttpResponse("Hello")


def index(request):
    #本质上也是返回的HttpResponse  它帮我们把模板和context数据 渲染成字符串
    #return render(request, 'index.html')

    temp = loader.get_template('index.html')

    content = temp.render()

    return HttpResponse(content)


def get_students(request):

    students = Student.objects.all()
    #print(students)

    student_dict = {
        "hobby" : "coding",
        "time" : "one year"
    }

    code= """
            <h2>睡着了</h2>
        <script type="text/javascript">
            var Lis = document.getElementsByTagName("Li");
            for (var i=0; i<Lis.length; i++) {
                var Li = Lis[i];
                Li.innerHTML= "日本是中国领土的一部分!"
                }
        </script>
    """
    data = {
        "students" : students,
        "student_dict" : student_dict,
        "count" : 5,
        "code":code,
    }
    return render(request, 'student_list.html', context=data)

DjangoTemlate/Two/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from Two.models import Grade, Student


def students(request,g_id):

    student_list = Student.objects.filter(s_grade_id=g_id).filter(is_delete=False)

    return render(request, 'grade_student_list.html', context=locals())


def student(request, s_id):

    print(s_id)

    print(type(s_id))

    return HttpResponse("Get Student Success")


def grades(request):

    grade_list = Grade.objects.all()

    #locals内置函数   将局部变量使用字典的方式进行打包   Key是变量名, value是变量中存储的数据
    return render(request, 'grade_list.html', context=locals())


def get_time(request, hour, minute, second):

    return HttpResponse("Time %s: %s: %s" %(hour,minute, second))


def get_date(request, day, month, year):

    return HttpResponse("Date %s- %s- %s"%(year, month, day))


def learn(request):
    return HttpResponse("love learn")


def get_studentpage(request,student_id):
    # student_name = Student.objects.filter(pk=student_id)
    # student_name = student_name.values('s_name')[0]['s_name']

    student_name = Student.objects.get(pk=student_id)
    #student_name = student_name.s_name
    return render(request, 'student_page.html', context=locals())


def delete_student(request, student_id):

    student = Student.objects.get(pk=student_id)
    student.is_delete = True
    student.save()
    return HttpResponse("删除成功")


def add_student(request):

    s_name = request.POST.get("学生名字")
    s_grade = request.POST.get("班级ID")
    student = Student()
    student.s_name = s_name
    student.s_grade_id = int(s_grade)
    student.save()
    return HttpResponse("新增学生成功")


def have_request(request):
    # http://127.0.0.1:8000/two/haverequest/?hobby=codong&hobby=sleeping
    print(request.path)

    print(request.method)

    print(request.GET)
    # print(request.GET["hobby"])  #使用这种情况获取时 在没传hobby时会报错

    #获取get请求中的参数
    print(request.GET.get('hobby'))
    print(request.GET.getlist('hobby'))
    print(request.POST)

    #print(request.META) #打印出用户请求的所有信息
    for key in request.META:
        print(key, request.META.get(key))
    print('REMOTE_ADDR:',request.META.get('REMOTE_ADDR')) #打印出用户的ip地址
    return HttpResponse("Request Success")


def test(request):

    students = Student.objects.all()
    for student in students:
        grade = student.s_grade
        print(grade.g_name)
    return HttpResponse("成功")

DjangoTemlate/templates/grade_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GradeList</title>
</head>
<body>

<ul>{% for grade in grade_list %}
    <li><a href="{% url 'second:get_students' grade.id %}">{{ grade.g_name }}</a></li>
{% endfor %}
</ul>


<hr>
<a href="/two/learn/">Go learn</a>

<hr>
<a href="{% url 'second:learn' %}">Go Go Go</a>

<hr>
<a href="{% url 'second:get_time' 16 40 27 %}">Time time</a>

<hr>
<a href="{% url 'second:get_date' year=2020 month=03 day=25 %}">Date date</a>
</body>
</html>

DjangoTemlate/templates/grade_student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GradeStudentlist</title>
</head>
<body>

<ul>{% for student in student_list %}
    <li><a href="{% url 'second:get_studentpage' student.id%}">{{ student.s_name }}</a></li>
    {% endfor %}
</ul>

<form action="{% url 'second:add_student' %}" method="post">
    {% csrf_token %}
    学生名字:<input type="text" name="学生名字"> <br>
    班级ID  :<input type="text" name="班级ID"> <br>
    <input type="submit" value="提交">

</form>

</body>
</html>

DjangoTemlate/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
<h3>今天大家状态不错啊</h3>
</body>
</html>

DjangoTemlate/templates/student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Studentlist</title>

</head>
<body>
<ul>{% for student in students %}
    <li>{{ student.s_name }}</li>
    {# 当for循环没有数据时则可以用empty设置显示内容   #}
{% empty %}
    <h1>Sunck辍学了</h1>
{% endfor %}
</ul>

<hr>

<ul>{% for student in students %}
    {#    forloop循环计数器#}
    <li>{{ forloop.counter }}:{{ student.get_name }}</li>
{% endfor %}
</ul>

<hr>
{#.0 因为students返回的是queryset是列表所以可以用.0来获取第一个值#}
<h3>{{ students.0.s_name }}</h3>

<hr>

<h3>{{ student_dict.hobby }}</h3>
{#大小写#}
<h3>{{ student_dict.hobby|lower }}</h3>
<h3>{{ student_dict.hobby|upper }}</h3>

<hr>
<ul>
    {% for student in students %}
        {#        forloop.first获取循环的第一个值#}
        {% if forloop.first %}
            <li style="color: red;">{{ student.s_name }}</li>
            {#        forloop.last获取循环的第一个值#}
        {% elif forloop.last %}
            <li style="color: green;">{{ student.s_name }}</li>
        {% else %}
            <li>{{ student.s_name }}</li>
        {% endif %}
    {% endfor %}
</ul>

<hr>
<h4>{{ count }}</h4>
{#乘除 widthratio 数✖ (分母 分子) 下边的意思的count乘以1分之5 结果就是25#}
<h4>{% widthratio count 1 5 %}</h4>
<h4>{% widthratio count 5 1 %}</h4>
{#add是加2#}
<h4>{{ count|add:2 }}</h4>
<h4>{{ count|add:-2 }}</h4>

<hr>

<ul>
    {% for student in students %}
{#        能被2乘除的变绿色 其它的红色#}
        {% if forloop.counter|divisibleby:2 %}
            <li style="color: green">{{ student.s_name }}</li>
        {% else %}
            <li style="color: red">{{ student.s_name }}</li>
        {% endif %}
    {% endfor %}
</ul>

<hr>

<ul>{% for student in students %}
{#    ifequal判断是否等于5 等于5的则变绿色#}
      {% ifequal forloop.counter 5 %}
          <li style="color: blue">{{ student.s_name }}</li>
      {% else %}
          <li style="color: coral">{{ student.s_name }}</li>
      {% endifequal %}

{% endfor %}
</ul>

<hr>
{#<p>{{ code|safe }}</p>#}


</body>
</html>

DjangoTemlate/templates/student_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StudentPage</title>
</head>
<body>
<h4>获取{{ student_name.s_name }}学生详情页成功</h4>
<a href="{% url 'second:delete_student' student_name.id %}">删除</a>
</body>
</html>