DjangoView/App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^hello/', views.hello, name='hello'),
    url(r'^getticket/', views.get_ticket, name='get_ticket'),
    url(r'^getinfo/', views.get_info, name='get_info'),
    url(r'^setcookie/', views.set_cookie, name='set_cookie'),

    url(r'^getcookie/', views.get_cookie, name='get_cookie'),
    url(r'^login/', views.login, name='login'),

    url(r'^dologin/', views.dologin, name='dologin'),

    url(r'^mine/', views.mine, name='mine'),

    url(r'^logout/', views.logout, name='logout'),
]

DjangoView/DjangoView/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('App.urls', namespace='app')),
    url(r'^two/', include('Two.urls', namespace='two')),
]

DjangoView/Two/urls.py
from django.conf.urls import url

from Two import views

urlpatterns = [
    url(r'^hello/', views.hello, name='hello'),

    url(r'^login/', views.login, name='login'),

    url(r'^mine/', views.mine, name='mine'),

    url(r'^logout/', views.logout, name='logout'),

    url(r'^register/', views.register, name='register'),

    url(r'^studentlogin/', views.student_login, name='studentlogin'),

    url(r'^studentmine/', views.student_mine, name='studentmine'),
]

DjangoView/App/models.py
from django.db import models

# Create your models here.

DjangoView/Two/models.py
from django.db import models

class Student(models.Model):
    s_name = models.CharField(max_length=16,unique=True)
    s_password = models.CharField(max_length=128)
    s_token = models.CharField(max_length=256)

DjangoView/App/views.py
import base64
import random

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render,redirect

# Create your views here.
from django.urls import reverse


def hello(request):

    response = HttpResponse()

    # response.content = "德玛西亚"
    #
    # response.status_code = 404

    response.write("听说马桶堵了")

    response.flush()

    return response


def get_ticket(request):

    #反向解析
    url = reverse('app:hello')
    print(url)

    if random.randrange(10) > 5:
        #重定向的2种方法
        return redirect(url)
        # return HttpResponseRedirect(url)

    return HttpResponse("恭喜你抢到票了")


def get_info(request):

    data = {
        "msg":"ok",
        "status": 200
    }
    #以json格式返回数据
    return JsonResponse(data=data)


def set_cookie(request):

    response = HttpResponse("设置cookie")

    response.set_cookie('username', 'Rock')

    return response


def get_cookie(request):

    username = request.COOKIES.get("username")

    return HttpResponse(username)


def login(request):
    return render(request, 'login.html')


def dologin(request):

    uname = request.POST.get('uname')

    #因为cookie默认不支持中文, 所以在接收到输入中文时先转码存
    uname = str(base64.b64encode(uname.encode("utf-8")), "utf-8")

    #反向解析到mine
    response = HttpResponseRedirect(reverse('app:mine'))

    #max_age设置cookie过期时间  max_age=60代表1分钟后过期
    # response.set_cookie('uname', uname, max_age=60)

    response.set_signed_cookie('uname', uname, salt="Rock", max_age=10)

    return response


def mine(request):
    '''
    因为在设置cookie时使用了过期时间, 所以在获取到过期后的cookie时是None会报错
    利用python的异常捕获 当try里报错时 执行except里的
    '''
    # uname = request.COOKIES.get('uname')
    try:
        #如果cookie是加密的  在获取时使用这种方式进行解密 salt参数值同加密时的
        uname = request.get_signed_cookie('uname', salt="Rock")

        #判断cookie是否还在  如果在正常返回 如果不在则跳转到登录页面
        if uname:
            # 返回时解码反在if里边 因为cookie过期后 返回None  base解码时会报错所以反正if里边
            uname = str(base64.b64decode(uname), "utf-8")
            return render(request, 'mine.html', context={"uname": uname})
        return HttpResponseRedirect(reverse('app:login'))

    except:

        return HttpResponseRedirect(reverse('app:login'))



def logout(request):

    response = redirect(reverse('app:login'))

    #删除浏览器cookie   让浏览器把cookie变过期
    response.delete_cookie('uname')

    return response

DjangoView/Two/views.py
import hashlib
import random
import time

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect


# Create your views here.
from django.urls import reverse

from Two.models import Student


def hello(request):

    return HttpResponse("Hello Two")


def login(request):
    #django中session的默认过期时间是14天  默认存在django_session表中
    #使用的base64加密  在前部添加了一个混淆串
    if request.method == "GET":
        return render(request, 'two_login.html')
    elif request.method == "POST":

        username = request.POST.get("username")

        request.session["username"] = username

        return HttpResponse("登录成功")



def mine(request):

    username = request.session.get("username")

    return render(request, 'two_mine.html', context=locals())


def logout(request):

    response = redirect(reverse('two:mine'))

    #删除session  这种删除方式会在django_session表中留下垃圾数据
    #del request.session['username']

    #删除浏览器的cookie
    #response.delete_cookie('sessionid')

    #session和cookie一起删 这种方式不会留下垃圾数据
    request.session.flush()

    return response


def register(request):

    if request.method == "GET":
        return render(request, 'student_register.html')
    elif request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        try:
            student = Student()
            student.s_name = username
            student.s_password = password
            student.save()

        except Exception as e:
            return redirect(reverse("two:register"))
        return HttpResponse("注册成功")


def student_login(request):
    if request.method == "GET":
        return render(request, 'student_login.html')
    elif request.method == "POST":
        username = request.POST.get("username")

        password = request.POST.get("password")

        students = Student.objects.filter(s_name=username).filter(s_password=password)

        if students.exists():

            student = students.first()

            ip = request.META.get("REMOTE_ADDR")

            token = generate_token(ip,username)

            student.s_token= token

            student.save()

            # response = HttpResponse("用户登录成功")
            #
            # response.set_cookie("token", token)
            #
            # return response

            data = {
                "status":200,
                "msg": "login success",
                "token": token
            }
            return JsonResponse(data=data)
        # return redirect(reverse('two:studentlogin'))

        data = {
            "status":800,
            "msg": "verify fail"
        }
        return JsonResponse(data)
def generate_token(ip, username):

    c_time = time.ctime()
    print(type(c_time))
    print(c_time)
    r = username

    return hashlib.new("md5", (ip + c_time + r).encode("utf-8")).hexdigest()


def student_mine(request):

    token = request.COOKIES.get("token")

    try:
        student = Student.objects.get(s_token=token)
    except Exception as e:
        return redirect(reverse('two:studentlogin'))

    # return HttpResponse(student.s_name)
    data = {
        "msg":"ok",
        "status":200,
        "data":{
            "username": student.s_name
        }
    }
    return JsonResponse(data=data)

DjangoView/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>

<form action="{% url 'app:dologin' %}" method="post">

    <span>用户名:</span> <input type="text" placeholder="请输入用户名" name="uname">

    <br>

    <button>登录</button>

</form>



</body>
</html>

DjangoView/templates/mine.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mine</title>
</head>
<body>

<h2>欢迎回来:{{ uname }}</h2>

<a href="{% url 'app:logout' %}">退出</a>

</body>
</html>

DjangoView/templates/student_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StudentLogin</title>
</head>
<body>

<form action="{% url 'two:studentlogin' %}" method="post">

    <span>用户名:</span><input type="text" name="username" placeholder="请输入用户名">
    <br>
    <span>密码:</span><input type="text" name="password" placeholder="请输入你的银行卡密码">
    <br>

    <button>登录</button>

</form>

</body>
</html>

DjangoView/templates/student_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StudentRegister</title>
</head>
<body>

<form action="{% url 'two:register' %}" method="post">

    <span>用户名:</span><input type="text" name="username" placeholder="请输入用户名">
    <br>
    <span>密码:</span><input type="text" name="password" placeholder="请输入你的银行卡密码">
    <br>

    <button>注册</button>
</form>

</body>
</html>

DjangoView/templates/two_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>

<form action="{% url 'two:login' %}" method="post">

    <span>用户名:</span><input type="text" placeholder="请输入用户名" name="username">

    <br>

    <button>登录</button>

</form>


</body>
</html>

DjangoView/templates/two_mine.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mine</title>
</head>
<body>

<h2>欢迎回来:{{ username }}</h2>

<a href="{% url 'two:logout' %}">退出</a>
</body>
</html>