TestPlatform/App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^hello/', views.hello, name='hello'),
    url(r'^addcase/', views.addcase, name='addcase'),
    url(r'^module/', views.module, name='module'),
    url(r'^getcases/(\d+)/', views.get_cases, name='get_cases'),
    url(r'^runcase/(\d+)/', views.run_case, name='run_case'),
]

TestPlatform/TestPlatform/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('App.urls', namespace='app'))
]

TestPlatform/App/models.py
from django.db import models

# Create your models here.

class Module(models.Model):

    m_name = models.CharField(max_length=24, unique=True)


class Case(models.Model):

    c_name = models.CharField(max_length=24)
    c_method = models.CharField(max_length=10)
    c_url = models.CharField(max_length=256)
    c_header = models.CharField(max_length=1000, null=True, blank=True)
    c_data = models.CharField(max_length=1000, null=True, blank=True)
    c_code = models.CharField(max_length=24)
    c_result = models.CharField(max_length=100)
    c_module = models.ForeignKey(Module)

TestPlatform/App/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render

# Create your views here.
from App.models import Case, Module
from App.utils import run_main
import json

def hello(request):
    return HttpResponse("Hello")


def addcase(request):

    if request.method == 'GET':
        m_name = Module.objects.all().order_by('id')
        return render(request, 'addcase.html', context=locals())
    elif request.method == 'POST':
        m_name = request.POST.get('模块')


        c_name = request.POST.get('用例名称')
        c_method = request.POST.get('调用方式')
        c_url = request.POST.get('url')
        c_header = request.POST.get("请求头")
        c_data = request.POST.get('请求数据')
        c_code = request.POST.get('返回状态码')
        c_result = request.POST.get('期望结果')

        case = Case()
        case.c_name = c_name
        case.c_method = c_method
        case.c_url = c_url
        case.c_header = c_header
        case.c_data = c_data
        case.c_code = c_code
        case.c_result = c_result
        c_module_id = Module.objects.filter(m_name=m_name)
        # print(c_module_id.values())
        case.c_module_id = c_module_id[0].id
        case.save()

        return HttpResponse("添加成功")





def module(request):

    modules = Module.objects.all().order_by('id')

    return render(request, 'module_case_library.html', context=locals())

def get_cases(request,m_id):
    if request.method == 'GET':
        case_list = Case.objects.filter(c_module_id=m_id)
        return render(request, 'cases_list.html', context=locals())


def run_case(request,c_id):

    case = Case.objects.get(pk=c_id)
    url = case.c_url
    method = case.c_method
    data = case.c_data
    header = case.c_header
    include_result = case.c_result
    # print(url,method,data,header)
    result = run_main(url=url,method=method, data=eval(data), header=eval(header))
    # print(include_result)
    # print(result)
    if include_result in result:
        data = {
            '返回结果': result,
            '是否通过': 'Pass',
        }
        return JsonResponse(data)
    else:
        data = {
            '返回结果':result,
            '是否通过': 'Fail',
        }
        return JsonResponse(data)

TestPlatform/templates/addcase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add_Case</title>
</head>
<body>

<form action="{% url 'app:addcase' %}" method="post">
    {% csrf_token %}
    <select name="模块">
        {% for foo in m_name %}
            <option value="{{ foo.m_name }}">{{ foo.m_name }}</option>
        {% endfor %}

    </select>
    <br>
    <br>
    <span>用例名称:</span><input type="text" style="width:250px; height:30px;" name="用例名称" placeholder="请输入用例名称">
    <br>
    <br>
    <span>调用方式:</span><input type="text" style="width:200px; height:20px;" name="调用方式" placeholder="请输入调用方式">
    <br>
    <br>
    <span>url:</span><input type="text" style="width:800px; height:25px;" name="url" placeholder="请输入url">
    <br>
    <br>
    <span>请求头:</span><input type="text" style="width:550px; height:90px;" name="请求头" placeholder="请输入请求头">
    <br>
    <br>
    <span>请求数据:</span><input type="text" style="width:550px; height:90px;" name="请求数据" placeholder="请输入请求数据">
    <br>
    <br>
    <span>返回状态码:</span><input type="text" style="width:200px; height:20px;" name="返回状态码" placeholder="请输入返回状态码">
    <br>
    <br>
    <span>期望结果:</span><input type="text" style="width:400px; height:50px;" name="期望结果" placeholder="请输入期望结果">
    <br>
    <br>
    <button>提交</button>
</form>


</body>
</html>

TestPlatform/templates/cases_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Case_List</title>


</head>
<body>

<ul>{% for case in case_list %}
    <li>
        用例名称:{{ case.c_name }}<br>调用方式:{{ case.c_method }}<br>url:{{ case.c_url }}<br>请求头:{{ case.c_header }}<br>请求数据:{{ case.c_data }}<br>返回状态码:{{ case.c_code }}<br>期望结果:{{ case.c_result }}
    </li>
        <br>
        <form target="iframe{{ case.id }}" action="{% url 'app:run_case' case.id %}" method="post">
            <button>执行</button>
            {% csrf_token %}
            <table border="1" cellspacing="10" cellpadding="20" style="width:300px; height:40px;">
                <tr>
                    <th colspan="2">OutPut</th>
                </tr>
                <tr>
                    <td width="280px">
                        <iframe name="iframe{{ case.id }}"></iframe>
                    </td>
                </tr>
            </table>

        </form>
        <br>

    {% endfor %}
    </ul>
    <br>



</body>
</html>

TestPlatform/templates/module_case_library.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Module_Case_Library</title>
</head>
<body>
<ul>
    {% for module in modules %}
        <li><a href="{% url 'app:get_cases' module.id %}">{{ module.m_name }}</a></li>
    {% endfor %}

</ul>



</body>
</html>